In [2]:
from __future__ import division#파이썬 3이상에서는 불필요, 나누기 연산시 캐스팅과 관련된 기능
from numpy.random import randn
import numpy as np
import os
import matplotlib.pyplot as plt
np.random.seed(1234)
plt.rc('figure',figsize=(10,6))
from pandas import Series,DataFrame
import pandas as pd
np.set_printoptions(precision=4,threshold=500)
pd.options.display.max_rows = 100

In [3]:
%matplotlib inline

In [6]:
df1 = DataFrame({'key':['b','b','a','c','a','a','b'],
                'data1': range(7)})
df2 = DataFrame({'key':['a','b','d'],
                'data2':range(3)})
print(df1)
print()
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

  key  data2
0   a      0
1   b      1
2   d      2


In [10]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [11]:
pd.merge(df1,df2,on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [13]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [12]:
df3 = DataFrame({'lkey':['b','b','a','c','a','a','b'],
                'data1':range(7)})
df4 = DataFrame({'rkey':['a','b','d'],
                'data2':range(3)})
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [18]:
left = DataFrame({'key1':['foo','boo','bar'],
                 'key2':['one','two','three'],
                 'lval':[1,2,3]})
right = DataFrame({'key1':['foo','boo','bar','bar'],
                  'key2':['one','one','one','two'],
                  'rval':[4,5,6,7]})
pd.merge(left,right,on=['key1','key2'],how = 'right')

key1 key2  lval  rval
0  foo  one   1.0     4
1  boo  one   NaN     5
2  bar  one   NaN     6
3  bar  two   NaN     7

In [19]:
pd.merge(left,right,on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  boo    two     2    one     5
2  bar  three     3    one     6
3  bar  three     3    two     7

In [21]:
pd.merge(left,right,on='key1',suffixes=('_left','_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  boo       two     2        one     5
2  bar     three     3        one     6
3  bar     three     3        two     7

In [24]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],
                  'value': range(6)})
right1 = DataFrame({'group_val':[3.5,7]},index=['a','b'])

In [25]:
right1

group_val
a        3.5
b        7.0

In [26]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [27]:
pd.merge(left1,right1,left_on='key',right_index=True,how ='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [28]:
lefth = DataFrame({'key1':['Ohio','Ohio','Ohio','Nevada','Nevada'],
                  'key2':[2000,2001,2002,2001,2002],
                  'data':np.arange(5)})
righth = DataFrame(np.arange(12).reshape((6,2)),
                  index = [['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],
                          [2001,2000,2000,2000,2001,2002]],
                  columns=['event1','event2'])

In [29]:
lefth

key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [30]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [34]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index = True)

key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11
3  Nevada  2001     3       0       1

In [39]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [44]:
s1 = Series([0,1],index=['a','b'])
s2 = Series([2,3,4],index=['c','d','e'])
s3 = Series([5,6],index=['f','g'])

In [49]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [51]:
s4 = pd.concat([s1*5,s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [53]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [54]:
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [55]:
result = pd.concat([s1,s1,s3],keys=['one','two','three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [56]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [58]:
df1 = DataFrame(np.arange(6).reshape(3,2),index = ['a','b','c'],columns=['one','two'])
df2 = DataFrame(5+np.arange(4).reshape(2,2),index= ['a','c'],columns=['three','four'])

In [59]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [60]:
df2

three  four
a      5     6
c      7     8

In [64]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'],sort= False)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [65]:
pd.concat({'level1':df1,'level2':df2},axis=1,sort=True)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [66]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'],names =['upper','lower'],sort=True)

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [68]:
pd.concat([df1,df2],ignore_index=True,sort= True)

four  one  three  two
0   NaN  0.0    NaN  1.0
1   NaN  2.0    NaN  3.0
2   NaN  4.0    NaN  5.0
3   6.0  NaN    5.0  NaN
4   8.0  NaN    7.0  NaN

In [84]:
a = Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
           index=['f', 'e', 'd', 'c', 'b', 'a'])
b = Series(np.flip(np.arange(len(a), dtype=np.float64),axis=0),
           index=['f', 'e', 'd', 'c', 'b', 'a'])
print(a)
b[-1] = np.nan
print(b)

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
f    5.0
e    4.0
d    3.0
c    2.0
b    1.0
a    NaN
dtype: float64


In [87]:
np.where(pd.isnull(a),b,a)#조건식이 맞으면 b, 틀리면 a

array([5. , 2.5, 3. , 3.5, 4.5, nan])

In [89]:
b.combine_first(a)#combine_first: 겹치는 인덱스의 값을 b에 맞춤

f    5.0
e    4.0
d    3.0
c    2.0
b    1.0
a    NaN
dtype: float64